### ISSUE TITLE
Leap year computation is incorrect

### ISSUE THREAD

**Issue by messju** [daishisystems/month#2]
Hi,

just skimming over this library I recognized, that isLeapYear is only checking for the year modulo 4.

The correct defintion of isLeapYear would be: 
Every 4 years it's a leap year,
but every 100 years the leap year is skipped (1900 was no leap year)
but every 400 years the leap year is not skipped (2000 was a leap year).

Just my 2ct
messju

**Comment by daishisystems** [comment]
Thanks for pointing that out. I’ve applied a fix in [this commit.](https://github.com/daishisystems/month/commit/605999902d380601cefed68acef9612e28c25f17)
Fortunately, the issue would not have manifested 2100-01-01!
